logging:
  level:
    root: trace

management:
  endpoints:
    web:
      expose: "*"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

---

spring:
  profiles: docker
  data:
    mongodb:
      host: mongo
      port: 27017